[book]
title = "Chrysalis Documentation"
authors = ["Sebastian Heusser <sebastian.heusser@iota.org>"]
language = "en"
multilingual = false
src = "docs"

[output.html]
theme = "theme"
additional-css = ["./theme/css/custom.css", "./theme/css/custom/header.css", "./theme/css/custom/dtmo.css", "./theme/css/custom/mermaid.css"]
additional-js = ["./theme/javascript/meta-nav.js", "./theme/javascript/mermaid.min.js", "./theme/javascript/mermaid-init.js"]

default-theme = "iota"
git-repository-url = "https://github.com/iotaledger/chrysalis-docs"
git-repository-icon = "fa-github"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[output.linkcheck]

